global:
  resolve_timeout: 1m

templates: 
- 'templates/*.tmpl'

route:
  receiver: 'telegram'
  group_by: []            # Empty list to avoid grouping alerts
  group_wait: 0s          # Send notifications immediately
  group_interval: 1s      # Set a minimal interval for ongoing alerts
  repeat_interval: 4h     # Repeat notifications for ongoing alerts every 4 hours

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'           # Put your telegram bot token here
        chat_id: YOUR_TELEGRAM_USER_ID                 # Put your telegram user id here
        message: '{{ template "telegram.message" . }}' # Use your custom template here
