global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts/alert.rules

scrape_configs:
  # Prometheus metrics
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  # Telegraf Prometheus metrics
  - job_name: telegraf
    static_configs:
      - targets:
          - nym-telegraf:9273
