{
 "title": "NYM Mixnode Dashboard",
 "tags": [
  "nym",
  "mixnode"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "mixnode",
    "query": {
     "query": "label_values(http_nymcollector_avg_uptime,mixnode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mixnode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets received since startup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_received_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received since startup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_nymcollector_received_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets sent since startup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_sent_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets sent since startup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_nymcollector_sent_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets dropped since startup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_dropped_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets dropped since startup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_nymcollector_dropped_since_startup{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_mix_id{mixnode=\"$mixnode\"}",
     "legendFormat": "{{node_status}}"
    }
   ]
  },
  {
   "title": "Packets since last polling",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_received_since_last_update",
     "legendFormat": "received"
    },
    {
     "expr": "http_nymcollector_sent_since_last_update",
     "legendFormat": "sent"
    },
    {
     "expr": "http_nymcollector_dropped_since_last_update",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Packets since last polling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_nymcollector_received_since_last_update",
     "legendFormat": "received"
    },
    {
     "expr": "http_nymcollector_sent_since_last_update",
     "legendFormat": "sent"
    },
    {
     "expr": "http_nymcollector_dropped_since_last_update",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Performance [24h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_nymcollector_avg_uptime{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance [24h]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_avg_uptime{mixnode=\"$mixnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_nymcollector_report_last_day",
     "legendFormat": "last_day"
    },
    {
     "expr": "http_nymcollector_report_last_hour",
     "legendFormat": "last_hour"
    },
    {
     "expr": "http_nymcollector_report_uptime",
     "legendFormat": "now"
    }
   ]
  },
  {
   "title": "Stake saturation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_stake_saturation{mixnode=\"$mixnode\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(http_nymcollector_total_delegation{mixnode=\"$mixnode\"}/1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(http_nymcollector_total_delegation{mixnode=\"$mixnode\"}/1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards: Operator commission",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_rewards_operators{mixnode=\"$mixnode\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards: Staking commission",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_nymcollector_rewards_personnal{mixnode=\"$mixnode\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards: Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(http_nymcollector_rewards_operators + http_nymcollector_rewards_personnal{mixnode=\"$mixnode\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total delegations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(http_nymcollector_rewards_operators + http_nymcollector_rewards_personnal{mixnode=\"$mixnode\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}